### ISSUE TITLE
Support propagation between Scala.Rx for Scala and Scala.Rx for Scala.js

### ISSUE THREAD

**Issue by psnively** [lihaoyi/scala.rx#31]
Please consider implementing change propagation between Scala.js and Scala, possibly with a typeclass for serialization, along the lines of autowire. In other words, it would be great to have FRP between the front and back ends, like autowire provides for AJAX.

**Comment by lihaoyi** [comment]
This would be cool and I have done it before. I can be done out of the box with some fiddling. What support do you need? =P

**Comment by psnively** [comment]
Unfortunately, I don't know. :-)

If you'll pardon the handwaving, I basically want to be able to have the front-end observe changes on the back end, react to them, and also have user interactions with the front end propagate changes to the back end. So the general use-case is very much like what you'd get from using any front-end framework with, e.g. websockets (and indeed, it seems that websockets could/should be the transport layer for modern browsers and back-ends). So perhaps naïvely, this sounds to me like: pluggable transport with graceful fallback from websockets to long-polling etc. plus pluggable serialization (uPickle etc.) plus means of specifying remote observers/listeners = end-to-end FRP.

But perhaps all I really want is documentation on the "fiddling" that can be done today. I don't wish to be greedy when you're already providing so much of your great work. :-)

**Comment by lihaoyi** [comment]
What I've done before is you use a custom implicit to bind your `Rx[T]`s into your Scalatags `Frag`s. This implicit does two things:

- Generates a unique ID (randomly)
- Gives the ID to the generated Scalatags Frag 
- Leaves some inline Javascript to register the ID on the client in some global `Map[Int, dom.Element]`
- Adds an `Obs` on the `Rx` that propagates updates to the client over some transport (websockets, long-polling) so the client can update. In my case I just propagated the rendered `String`s

That's for one-directional flow, which is all Scala.Rx supports. If you want the client to call back to server, you'll need to use Autowire for that =P. You can easily make the magic-implicit only work for 

```
implicit def bind[T: upickle.Writer](rx: Rx[T])
```

In which case you can send any pickle-able stuff down to the client instead of just the rendered strings (my implicit only took `Rx[Frag]` so I could always stringify them)

Note that this is tricky for several reasons

- You need a stateful server! That means your load balancer must take note of which session goes to which machine, if your process crashes everyone's sessions are ruined until they refresh. Not terrible, and sites like Quora use this, and occasionally have a "please refresh the page to continue seeing updates" banner show because of this =P
- You need to manage your own lifetimes! Your Rx's on the server don't know when the client has stopped listening to each particular one. If the client has gone away, or some portion of the client has re-rendered, the Rxs on the server and the stubs  in the global registry won't go away until you clear them manually. This will be easier on the server with the new version of Scala.rx that's coming out, but on the client it's still a pain. 

Hope this was useful =)
