### ISSUE TITLE
Documentation and examples for "ownership context" and "data context"

### ISSUE THREAD

**Issue by ajaychandran** [lihaoyi/scala.rx#63]
Version 0.3.x introduces the concepts of "ownership context" and "data context". I have not found any substantial (real-world) examples for these concepts, like the ones demonstrated [here](https://vimeo.com/98477272) in a presentation for version 0.2.5.

Any help on this will be much appreciated.

Also, in the code below, why does `c` require an owning context?
```scala
import rx._
val a = Var(1)
val b = Var(2)
val c = Rx { a() + b() }
```

**Comment by Voltir** [comment]
I have several libraries that build on top of scala.rx, these two in particular have demo code associated with them that are good examples of "real world" uses involving ownership and data contexts:

https://github.com/Voltir/form.rx

https://github.com/Voltir/route.rx

**Comment by ajaychandran** [comment]
@Voltir Thanks for the links, will check them out.

Also, the code block above does compile when defined in a static scope.

**Comment by Voltir** [comment]
Er, right. I guess the answer to your question is that it uses the "top-level" context because the macro code knows it is statically defined and there can only ever be one instance of c (this is implemented as trickery with @compileTimeOnly). More generally basically any  Rx defined directly in an object' won't complain about needing an implicit owning context because of this static check.
