### ISSUE TITLE
Wrong value propagated to `Rx.now` in `Obs`

### ISSUE THREAD

**Issue by fkz** [lihaoyi/scala.rx#89]
I'm executing the following ammonite script:
```scala
import $ivy.`com.lihaoyi::scalarx:0.3.2`, rx._
object Example {
val v1 = Var(0)
val v2 = v1.map(identity)
val v3 = v1.map(identity).map(identity).map(identity)
def q(implicit trackDependency: Ctx.Data) = {
    if (v1() == 0) v2()
    else {
      val b = v3() != v2()
      if (b)
        103
      else
        17
    }
  }
val v = Rx { q }
val list = {
    var result = List.empty[Int]
    val obs = v.trigger { result = result :+ v.now }
    v1() = 1
    v1() = 2
    result
  }
}
println(Example.list)
```

The output of this code is nondeterministically sometimes `List(0, 103, 17)` and sometimes `List(0, 17)`. (actually, it seems to be `List(0, 17)` after the first run and `List(0, 103, 17)` for already compiled runs).
Only `List(0, 17)` is the correct result AFAICT, because 103 should never happen. `trigger` is supposed to be called only after all Rx's have stabilized as presented in the README.
It should only be called when `v1`, `v2`, `v3` have the same value, thus `b` should be always false at the time the `Obs` is reevaluated. Hence, we should be in the 17 case and `v.now` should be 17.

**Comment by Voltir** [comment]
So yea, 103 shouldnt happen because v2() should always equal v3() -- when these things actually evaluate, a priority queue of nodes to visit is set up, and I noticed something strange, starting here:

https://github.com/lihaoyi/scala.rx/blob/master/scalarx/shared/src/main/scala/rx/Rx.scala#L121

I think this following constraint should be true:
`assert(min.depth >= currentDepth, "What?")`
And indeed, when the `(0,17)` case occurs, it is true, but when then `(0,103,17)` it ends up being false! Have I forgotten how priority queues are supposed to work? Im pretty sure the repeated calls to deque should end up outputting in sorted order and values shouldn't "go backwards" like it appears to be doing.

@lihaoyi any ideas?
